package com.cn.wanxi.model.order;

public class WxTabOrderItem {
    private Integer id;

    private Integer categoryId1;

    private Integer categoryId2;

    private Integer categoryId3;

    private String spuId;

    private String skuId;

    private String orderId;

    private String name;

    private Integer price;

    private Integer num;

    private Integer money;

    private Integer payMoney;

    private String image;

    private Integer weight;

    private Integer postFee;

    private String isReturn;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getCategoryId1() {
        return categoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.category_id1
     *
     * @param categoryId1 the value for wx_tab_order_item.category_id1
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setCategoryId1(Integer categoryId1) {
        this.categoryId1 = categoryId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.category_id2
     *
     * @return the value of wx_tab_order_item.category_id2
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getCategoryId2() {
        return categoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.category_id2
     *
     * @param categoryId2 the value for wx_tab_order_item.category_id2
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setCategoryId2(Integer categoryId2) {
        this.categoryId2 = categoryId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.category_id3
     *
     * @return the value of wx_tab_order_item.category_id3
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getCategoryId3() {
        return categoryId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.category_id3
     *
     * @param categoryId3 the value for wx_tab_order_item.category_id3
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setCategoryId3(Integer categoryId3) {
        this.categoryId3 = categoryId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.spu_id
     *
     * @return the value of wx_tab_order_item.spu_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getSpuId() {
        return spuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.spu_id
     *
     * @param spuId the value for wx_tab_order_item.spu_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setSpuId(String spuId) {
        this.spuId = spuId == null ? null : spuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.sku_id
     *
     * @return the value of wx_tab_order_item.sku_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.sku_id
     *
     * @param skuId the value for wx_tab_order_item.sku_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setSkuId(String skuId) {
        this.skuId = skuId == null ? null : skuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.order_id
     *
     * @return the value of wx_tab_order_item.order_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.order_id
     *
     * @param orderId the value for wx_tab_order_item.order_id
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.name
     *
     * @return the value of wx_tab_order_item.name
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.name
     *
     * @param name the value for wx_tab_order_item.name
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.price
     *
     * @return the value of wx_tab_order_item.price
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.price
     *
     * @param price the value for wx_tab_order_item.price
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.num
     *
     * @return the value of wx_tab_order_item.num
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.num
     *
     * @param num the value for wx_tab_order_item.num
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.money
     *
     * @return the value of wx_tab_order_item.money
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.money
     *
     * @param money the value for wx_tab_order_item.money
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.pay_money
     *
     * @return the value of wx_tab_order_item.pay_money
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.pay_money
     *
     * @param payMoney the value for wx_tab_order_item.pay_money
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setPayMoney(Integer payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.image
     *
     * @return the value of wx_tab_order_item.image
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.image
     *
     * @param image the value for wx_tab_order_item.image
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.weight
     *
     * @return the value of wx_tab_order_item.weight
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.weight
     *
     * @param weight the value for wx_tab_order_item.weight
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.post_fee
     *
     * @return the value of wx_tab_order_item.post_fee
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public Integer getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.post_fee
     *
     * @param postFee the value for wx_tab_order_item.post_fee
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setPostFee(Integer postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_tab_order_item.is_return
     *
     * @return the value of wx_tab_order_item.is_return
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public String getIsReturn() {
        return isReturn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_tab_order_item.is_return
     *
     * @param isReturn the value for wx_tab_order_item.is_return
     *
     * @mbggenerated Wed Nov 20 15:26:33 CST 2019
     */
    public void setIsReturn(String isReturn) {
        this.isReturn = isReturn == null ? null : isReturn.trim();
    }
}